config/routes.rb
Rails.application.routes.draw do
  get 'pages/one'
  get 'pages/two'
  get 'pages/three'
  root 'pages#one'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def one
  end

  def two
  end

  def three
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="es">

  <head>
    <meta charset="UTF-8">
    <title>FirstApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    
    <!--CSS de Bootstrap -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css">
    
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>



  <body>
    <nav class="navbar navbar-inverse">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#">FirstApp</a>
        </div>
        <ul class="nav navbar-nav">
          
          <li><%= link_to "one", pages_one_path%></li>
          <li><%= link_to "two", pages_two_path%></li>
          <li><%= link_to "three", pages_three_path%></li>
        </ul>
      </div>
    </nav>

    <%= yield %>

    <!--jQuery 3.3.1 sin slim-->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>

    
    <!--Bootstrap JS 4.2.1-->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"></script>

  </body>
  
  </html>

app/views/pages/one.html.erb
<h1>Pages#one</h1>
<h1>Ivan Castillo Lopez</h1>
<p>Find me in app/views/pages/one.html.erb</p>

app/views/pages/three.html.erb
<h1>Pages#three</h1>

<h2> Esto es un título </h2> 

<%= lorem_ipsum(300) %>

app/views/pages/two.html.erb
<h1>Pages#two</h1>

<h3> Captura imagen routes </h3>

<%= image_tag 'routes.PNG' %>


<p>Find me in app/views/pages/two.html.erb</p>